#!/usr/bin/env node
/**
 * Copies the ABIs Foundry produced into packages/sdk so every off-chain app talks to
 * the contracts through one generated artifact.
 *
 * Hand-maintained ABI copies drift the moment a signature changes, and the failure is
 * silent — a keeper that decodes an old event shape simply sees nothing. Running this
 * in CI after `forge build` makes that drift a build failure instead.
 */
import {mkdirSync, readFileSync, writeFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "packages/sdk/src/abis");
mkdirSync(out, {recursive: true});

const artifacts = [
  ["PonsPrediction.sol", "PonsPrediction"],
  ["UniswapV3PonsOracle.sol", "UniswapV3PonsOracle"],
  ["CompositePonsOracle.sol", "CompositePonsOracle"],
];

const index = [];
for (const [file, name] of artifacts) {
  const path = join(root, "packages/contracts/out", file, `${name}.json`);
  const {abi} = JSON.parse(readFileSync(path, "utf8"));
  if (!Array.isArray(abi) || abi.length === 0) throw new Error(`empty ABI for ${name}`);
  writeFileSync(
    join(out, `${name}.ts`),
    `// GENERATED by scripts/sync-abis.mjs - do not edit.\n` +
      `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
  index.push(`export {${name}Abi} from "./${name}.js";`);
  console.log(`wrote ${name}.ts (${abi.length} entries)`);
}
writeFileSync(join(out, "index.ts"), `// GENERATED by scripts/sync-abis.mjs - do not edit.\n${index.join("\n")}\n`);
