#!/usr/bin/env node
/**
 * Writes apps/web/.env.local from a deployment file.
 *
 * The web app reads addresses from build-time environment; this is what fills them in
 * from the single source of truth. Without it a fresh local deployment leaves the UI
 * reading a contract that no longer exists, which looks like a bug in the app rather
 * than a stale address.
 *
 *   node scripts/write-web-env.mjs deployments/31337.json http://127.0.0.1:8545
 */
import {readFileSync, writeFileSync} from "node:fs";
import {dirname, join} from "node:path";
import {fileURLToPath} from "node:url";

// Defaults are the same-origin proxy paths served by next.config.mjs rewrites, so a
// generated env works from any host rather than only on the machine running the stack.
const [, , source, rpc = "/rpc", apiBase = "/api"] = process.argv;
if (!source) {
  console.error("usage: write-web-env.mjs <deployment.json> [rpcUrl] [apiBase]");
  process.exit(1);
}

const d = JSON.parse(readFileSync(source, "utf8"));
const dest = join(dirname(fileURLToPath(import.meta.url)), "..", "apps", "web", ".env.local");

writeFileSync(
  dest,
  [
    "# Generated by scripts/write-web-env.mjs - do not edit; re-run the script instead.",
    `NEXT_PUBLIC_CHAIN_ID=${d.chainId}`,
    `NEXT_PUBLIC_PREDICTION_ADDRESS=${d.PonsPrediction}`,
    `NEXT_PUBLIC_ORACLE_ADDRESS=${d.PonsOracleAdapter}`,
    `NEXT_PUBLIC_PONS_ADDRESS=${d.PONS}`,
    `NEXT_PUBLIC_WETH_ADDRESS=${d.WETH}`,
    `NEXT_PUBLIC_POOL_ADDRESS=${d.PONSWETHPool}`,
    `NEXT_PUBLIC_RPC_URL=${rpc}`,
    `NEXT_PUBLIC_API_BASE=${apiBase}`,
    "",
  ].join("\n")
);
console.log(`wrote ${dest} for chain ${d.chainId}`);
