// GENERATED by scripts/sync-abis.mjs - do not edit.
export const CompositePonsOracleAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "pools",
        "type": "address[]",
        "internalType": "address[]"
      },
      {
        "name": "baseToken_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "quoteToken_",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "baseDecimals_",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "defaultTwapWindow_",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "maxDivergenceBps_",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "oracleVersion_",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "MAX_SOURCES",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_TWAP_WINDOW",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "baseToken",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "baseUnit",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "canQuote",
    "inputs": [
      {
        "name": "targetTimestamp",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "twapWindow",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "ok",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "reason",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "decimals",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "defaultTwapWindow",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "description",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "earliestAvailableTimestamp",
    "inputs": [],
    "outputs": [
      {
        "name": "earliest",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPrice",
    "inputs": [],
    "outputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "timestamp",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPriceAt",
    "inputs": [
      {
        "name": "targetTimestamp",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "twapWindow",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "meanTick",
        "type": "int24",
        "internalType": "int24"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getSpotPrice",
    "inputs": [],
    "outputs": [
      {
        "name": "price",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "tick",
        "type": "int24",
        "internalType": "int24"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "inspect",
    "inputs": [
      {
        "name": "targetTimestamp",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "twapWindow",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [
      {
        "name": "ticks",
        "type": "int24[]",
        "internalType": "int24[]"
      },
      {
        "name": "available",
        "type": "bool[]",
        "internalType": "bool[]"
      },
      {
        "name": "spreadBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxDivergenceBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "observationState",
    "inputs": [],
    "outputs": [
      {
        "name": "index",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "cardinality",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "cardinalityNext",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "oldest",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "newest",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "oracleVersion",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "poolLiquidity",
    "inputs": [],
    "outputs": [
      {
        "name": "total",
        "type": "uint128",
        "internalType": "uint128"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "quoteToken",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sourceAt",
    "inputs": [
      {
        "name": "i",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "pool",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "baseIsToken0",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sourceCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sourceLiquidity",
    "inputs": [],
    "outputs": [
      {
        "name": "liquidity",
        "type": "uint128[]",
        "internalType": "uint128[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "BaseDecimalsMismatch",
    "inputs": [
      {
        "name": "declared",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "onChain",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "BaseDecimalsTooLarge",
    "inputs": [
      {
        "name": "decimals",
        "type": "uint8",
        "internalType": "uint8"
      }
    ]
  },
  {
    "type": "error",
    "name": "BaseTokenNotInPool",
    "inputs": [
      {
        "name": "pool",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "base",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "DivergenceToleranceZero",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MeanTickOutOfRange",
    "inputs": [
      {
        "name": "mean",
        "type": "int56",
        "internalType": "int56"
      }
    ]
  },
  {
    "type": "error",
    "name": "NoSources",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PoolNotInitialised",
    "inputs": [
      {
        "name": "pool",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "QuoteIsZero",
    "inputs": [
      {
        "name": "medianTick",
        "type": "int24",
        "internalType": "int24"
      }
    ]
  },
  {
    "type": "error",
    "name": "QuoteTokenNotInPool",
    "inputs": [
      {
        "name": "pool",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "quote",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SourceUnavailable",
    "inputs": [
      {
        "name": "pool",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SourcesDiverged",
    "inputs": [
      {
        "name": "lowTick",
        "type": "int24",
        "internalType": "int24"
      },
      {
        "name": "highTick",
        "type": "int24",
        "internalType": "int24"
      },
      {
        "name": "spreadBps",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "toleranceBps",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "T",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TargetInFuture",
    "inputs": [
      {
        "name": "target",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "nowTs",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "TooManySources",
    "inputs": [
      {
        "name": "given",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "max",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "WindowStartUnderflow",
    "inputs": [
      {
        "name": "target",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "window",
        "type": "uint32",
        "internalType": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "WindowTooLong",
    "inputs": [
      {
        "name": "window",
        "type": "uint32",
        "internalType": "uint32"
      },
      {
        "name": "maxWindow",
        "type": "uint32",
        "internalType": "uint32"
      }
    ]
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroWindow",
    "inputs": []
  }
] as const;
