// GENERATED by scripts/sync-abis.mjs - do not edit.
export {PonsPredictionAbi} from "./PonsPrediction.js";
export {UniswapV3PonsOracleAbi} from "./UniswapV3PonsOracle.js";
export {CompositePonsOracleAbi} from "./CompositePonsOracle.js";
export {PonsBuybackBurnerAbi} from "./PonsBuybackBurner.js";
